### ISSUE TITLE
Compile time error - SLF4J: Class path contains multiple SLF4J binding.

### ISSUE THREAD

**Issue by jugraj77** [JPL-IMCE/jpl.omf.schema.tables#1] opened 2016-09-28 10:57 UTC
I am using sbt to compile this project. But during compiling of Scala source to target classes i am encountering this error. when sbt resolves dependencies it downloads two jars with same class "Staticloggerbinder.class" which results in this error. Could you please resolve this dependency issue? I have tried excluding the transitive dependencies but these two jars are used by too many libraries.
![compilation error](https://cloud.githubusercontent.com/assets/22496112/18911043/aea04338-8572-11e6-9e36-82ad820580ba.png)

**Comment by NicolasRouquette** [comment] 2016-09-28 14:26
There may be an SLF4J configuration issue; however, that is not what is the problem here.

The problem is that you're running on a Windows environment that does not have the [sed](https://en.wikipedia.org/wiki/Sed) utility typically found in Unix environments (e.g., Linux, Mac).

The SBT configuration uses external utilities to retrieve information about the project;
see: https://github.com/JPL-IMCE/jpl.omf.schema.tables/blob/master/build.sbt#L128

For the time being, replace in build.sbt the following lines:

```
      "CONTRIBUTORS" -> {
        val commit = Process("git rev-parse HEAD").lines.head
        val p1 = Process(s"git shortlog -sne --no-merges $commit")
        val p2 = Process(
          Seq("sed",
            "-e",
            """s|^\s*\([0-9][0-9]*\)\s*\(\w.*\w\)\s*<\([a-zA-Z].*\)>.*$|<tr><td align='right'>\1</td><td>\2</td><td>\3</td></tr>|"""))
        val whoswho = p1 #| p2
        whoswho.lines.mkString("\n")
      },
```

with:

```
      "CONTRIBUTORS" -> "",
```

This should let you run SBT on windows so that you can compile and publish if needed.
Note that generating the github pages also depends on having the (Graphviz 'dot' utility)[http://www.graphviz.org] available as well. 

Alternatively, you might consider installing a Unix environment in Windows such as [cygwin](http://cygwin.com). 

Please let me know if these suggestions work for you.
- Nicolas.

**Comment by jugraj77** [comment] 2016-09-28 15:52
Thanks Nicolas. I have followed your first suggestion of removing the git commands and it worked. I am following your work on Semantically formalizing sysml model using profile mechanism and ontologies. I have also read about into various ontologies developed by your group for generating sysml profiles for modeling patterns. 
  I was actually looking for those ontologies and profiles to use in my research regarding computational augmentation of system modeling. Are those publicly available?

**Comment by NicolasRouquette** [comment] 2016-09-28 17:39
Glad this works for you! 

I will close this issue: supporting Windows is an issue affecting all of our projects (see:  JPL-IMCE/imce.sbt.plugin/issues/19)

Thanks for your interest in our work; we're close to getting approvals to put in open source the rest of our ontological modeling technology, incl. JPL's ontologies for MBSE & related tools (profile generation, export, ...)

**Closed as completed by NicolasRouquette** 2016-09-28 17:39 UTC
